CREATE EXTERNAL TABLE ext_tpch.lineitem
(L_ORDERKEY BIGINT, --key
L_PARTKEY BIGINT,
L_SUPPKEY BIGINT,
L_LINENUMBER BIGINT,
L_QUANTITY DECIMAL(15,2),
L_EXTENDEDPRICE DECIMAL(15,2),
L_DISCOUNT DECIMAL(15,2),
L_TAX DECIMAL(15,2),
L_RETURNFLAG CHAR(1),
L_LINESTATUS CHAR(1),
L_SHIPDATE DATE,
L_COMMITDATE DATE,
L_RECEIPTDATE DATE,
L_SHIPINSTRUCT CHAR(25),
L_SHIPMODE CHAR(10),
L_COMMENT VARCHAR(44),
dummy text)
LOCATION ('pxf://path/to/lineitem.tbl*?PROFILE=HdfsTextSimple')
FORMAT 'TEXT' (DELIMITER '|');
