CREATE EXTERNAL TABLE ext_tpch.partsupp
(PS_PARTKEY BIGINT, --key
PS_SUPPKEY BIGINT, --key
PS_AVAILQTY INTEGER,
PS_SUPPLYCOST DECIMAL(15,2),
PS_COMMENT VARCHAR(199),
dummy text)
LOCATION ('pxf://path/to/partsupp.tbl*?PROFILE=HdfsTextSimple')
FORMAT 'TEXT' (DELIMITER '|');
